# Generated by Django 3.0.4 on 2020-03-31 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aemter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mitglied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('vorname', models.CharField(max_length=50)),
                ('strasse', models.CharField(max_length=50)),
                ('plz', models.CharField(max_length=5)),
                ('ort', models.CharField(max_length=50)),
                ('tel_festnetz', models.CharField(max_length=15, null=True)),
                ('tel_mobil', models.CharField(max_length=15, null=True)),
                ('mail_privat', models.CharField(max_length=50, null=True)),
                ('jabber_id', models.CharField(max_length=50, null=True)),
                ('amt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aemter.Amt')),
            ],
        ),
    ]
