# Generated by Django 3.0.7 on 2020-06-16 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prevmitgliedamt',
            old_name='member',
            new_name='members',
        ),
    ]
