# Generated by Django 3.0.7 on 2020-06-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0002_auto_20200616_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prevmitgliedamt',
            name='members',
            field=models.ManyToManyField(null=True, to='mitglieder.Mitglied'),
        ),
    ]
