# Generated by Django 3.0.3 on 2020-04-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0003_auto_20200404_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitglied',
            name='hausnr',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
