# Generated by Django 3.0.6 on 2020-06-29 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0004_auto_20200616_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalmitglied',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Mitglied'},
        ),
        migrations.AlterModelOptions(
            name='historicalmitgliedamt',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Zuordnung Mitglied-Amt'},
        ),
        migrations.AlterModelOptions(
            name='historicalmitgliedmail',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Zuordnung Mitglied-Mail'},
        ),
        migrations.AlterModelOptions(
            name='mitglied',
            options={'verbose_name': 'Mitglied', 'verbose_name_plural': 'Mitglieder'},
        ),
        migrations.AlterModelOptions(
            name='mitgliedamt',
            options={'verbose_name': 'Zuordnung Mitglied-Amt', 'verbose_name_plural': 'Zuordnungen Mitglied-Amt'},
        ),
        migrations.AlterModelOptions(
            name='mitgliedmail',
            options={'verbose_name': 'Zuordnung Mitglied-Mail', 'verbose_name_plural': 'Zuordnungen Mitglied-Mail'},
        ),
    ]
