# Generated by Django 3.0.3 on 2020-06-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0004_auto_20200616_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmitgliedamt',
            name='amtszeit_beginn',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='historicalprevmitgliedamt',
            name='amtszeit_beginn',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='historicalprevmitgliedamt',
            name='amtszeit_ende',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='mitgliedamt',
            name='amtszeit_beginn',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='prevmitgliedamt',
            name='amtszeit_beginn',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='prevmitgliedamt',
            name='amtszeit_ende',
            field=models.DateField(null=True),
        ),
    ]
