# Generated by Django 3.0.5 on 2020-05-11 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0004_historicalmitglied_historicalmitgliedamt_historicalmitgliedmail'),
        ('mitglieder', '0004_auto_20200420_1913'),
    ]

    operations = [
    ]
