# Generated by Django 3.0.5 on 2020-05-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0005_merge_20200511_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmitglied',
            name='hausnr',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
