# Generated by Django 3.0.6 on 2020-06-11 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0006_auto_20200511_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalmitgliedamt',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical mitglied amt'},
        ),
    ]
