# Generated by Django 3.0.3 on 2020-07-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0006_auto_20200716_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mitgliednummerpaar',
            name='mitglied',
        ),
        migrations.RemoveField(
            model_name='prevmitgliedamt',
            name='funktion',
        ),
        migrations.RemoveField(
            model_name='prevmitgliedamt',
            name='members',
        ),
        migrations.AddField(
            model_name='historicalmitgliedamt',
            name='amtszeit_ende',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='mitgliedamt',
            name='amtszeit_ende',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='HistoricalPrevMitgliedAmt',
        ),
        migrations.DeleteModel(
            name='MitgliedNummerPaar',
        ),
        migrations.DeleteModel(
            name='PrevMitgliedAmt',
        ),
    ]
