# Generated by Django 3.0.3 on 2020-07-19 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0010_auto_20200719_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmitgliedamt',
            name='amtszeit_count',
        ),
        migrations.RemoveField(
            model_name='mitgliedamt',
            name='amtszeit_count',
        ),
    ]
