# Generated by Django 3.0.6 on 2020-06-29 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0005_auto_20200629_0958'),
        ('checklisten', '0003_historicalaufgabe_historicalcheckliste_historicalchecklisteaufgabe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aufgabe',
            options={'verbose_name': 'Aufgabe', 'verbose_name_plural': 'Aufgaben'},
        ),
        migrations.AlterModelOptions(
            name='checkliste',
            options={'verbose_name': 'Checkliste', 'verbose_name_plural': 'Checklisten'},
        ),
        migrations.AlterModelOptions(
            name='checklisteaufgabe',
            options={'verbose_name': 'Zuordnung Checkliste-Aufgabe', 'verbose_name_plural': 'Zuordnungen Checkliste-Aufgabe'},
        ),
        migrations.AlterModelOptions(
            name='historicalaufgabe',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Aufgabe'},
        ),
        migrations.AlterModelOptions(
            name='historicalcheckliste',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Checkliste'},
        ),
        migrations.AlterModelOptions(
            name='historicalchecklisteaufgabe',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Zuordnung Checkliste-Aufgabe'},
        ),
        migrations.RenameField(
            model_name='historicalcheckliste',
            old_name='mitgliedAmt',
            new_name='amt',
        ),
        migrations.RemoveField(
            model_name='checkliste',
            name='mitgliedAmt',
        ),
        migrations.AddField(
            model_name='checkliste',
            name='amt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mitglieder.MitgliedAmt'),
        ),
        migrations.AddField(
            model_name='checkliste',
            name='mitglied',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mitglieder.Mitglied'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcheckliste',
            name='mitglied',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mitglieder.Mitglied'),
        ),
    ]
