# Generated by Django 3.0.6 on 2020-07-05 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aemter', '0002_auto_20200629_0956'),
        ('checklisten', '0004_auto_20200629_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalChecklisteRecht',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('abgehakt', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('checkliste', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='checklisten.Checkliste')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recht', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='aemter.Recht')),
            ],
            options={
                'verbose_name': 'historical Zuordnung Checkliste-Recht',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ChecklisteRecht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abgehakt', models.BooleanField(default=False)),
                ('checkliste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklisten.Checkliste')),
                ('recht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aemter.Recht')),
            ],
            options={
                'verbose_name': 'Zuordnung Checkliste-Recht',
                'verbose_name_plural': 'Zuordnungen Checkliste-Recht',
            },
        ),
    ]
