# Generated by Django 3.0.4 on 2020-03-31 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=50)),
                ('workload', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Organisationseinheit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Unterbereich',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AmtRecht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aemter.Amt')),
                ('recht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aemter.Recht')),
            ],
        ),
        migrations.AddField(
            model_name='amt',
            name='referat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aemter.Organisationseinheit'),
        ),
        migrations.AddField(
            model_name='amt',
            name='unterbereich',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aemter.Unterbereich'),
        ),
    ]
