# Generated by Django 3.0.5 on 2020-06-24 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aemter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funktion',
            name='organisationseinheit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aemter.Organisationseinheit'),
        ),
        migrations.AlterField(
            model_name='funktion',
            name='unterbereich',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aemter.Unterbereich'),
        ),
    ]
