# Generated by Django 3.0.3 on 2020-07-25 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aemter', '0002_auto_20200726_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorganisationseinheit',
            name='funktion_without_unterbereich_exists',
        ),
        migrations.RemoveField(
            model_name='organisationseinheit',
            name='funktion_without_unterbereich_exists',
        ),
    ]
