# Generated by Django 3.0.6 on 2020-06-10 14:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aemter', '0003_historicalamt_historicalamtrecht_historicalrecht_historicalreferat_historicalunterbereich'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalReferat',
            new_name='HistoricalOrganisationseinheit',
        ),
        migrations.AlterModelOptions(
            name='historicalorganisationseinheit',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical organisationseinheit'},
        ),
    ]
