# Generated by Django 3.0.3 on 2020-07-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aemter', '0003_auto_20200726_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganisationseinheit',
            name='funktion_without_unterbereich_exists',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organisationseinheit',
            name='funktion_without_unterbereich_exists',
            field=models.BooleanField(default=False),
        ),
    ]
