# Generated by Django 3.0.6 on 2020-06-11 08:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aemter', '0004_auto_20200610_1630'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalAmt',
            new_name='HistoricalFunktion',
        ),
        migrations.AlterModelOptions(
            name='historicalamtrecht',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical amt recht'},
        ),
    ]
