# Generated by Django 3.0.3 on 2020-07-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aemter', '0006_auto_20200726_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorganisationseinheit',
            name='funktion_without_unterbereich_exists',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='organisationseinheit',
            name='funktion_without_unterbereich_exists',
            field=models.IntegerField(default=0),
        ),
    ]
