# Generated by Django 3.0.3 on 2020-07-25 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aemter', '0007_auto_20200726_0049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalorganisationseinheit',
            old_name='funktion_without_unterbereich_exists',
            new_name='funktionen_ohne_unterbereich_count',
        ),
        migrations.RenameField(
            model_name='organisationseinheit',
            old_name='funktion_without_unterbereich_exists',
            new_name='funktionen_ohne_unterbereich_count',
        ),
    ]
