//Nutzen Sie dieses Template als Grundlage für die Spezifikation *einzelner* Use-Cases. Diese lassen sich dann per Include in das Use-Case Model Dokument einbinden (siehe Beispiel dort).
== Use-Case: Historie einsehen
===	Kurzbeschreibung
Um Änderungen an der Mitgliederdatenbank nachvollziehen und ggf. rückgängig machen zu können, +
möchte ich die Historie aller Änderungen einsehen können.

===	Kurzbeschreibung der Akteure

==== Interne Verwaltung
Die Mitglieder der internen Verwaltung sind für die Richtigkeit und Vollständigkeit der Daten in der Mitgliederdatenbank verantwortlich.

=== Vorbedingungen
//Vorbedingungen müssen erfüllt, damit der Use Case beginnen kann, z.B. Benutzer ist angemeldet, Warenkorb ist nicht leer...
. Der Akteur ist eingeloggt und verfügt über die Berechtigung, die Historie einsehen zu können.

=== Standardablauf (Basic Flow)
//Der Standardablauf definiert die Schritte für den Erfolgsfall ("Happy Path")

. Der Use Case beginnt, wenn der Akteur dem System mitteilt, dass er die Historie einsehen möchte.
. Das System listet die letzten n Einträge der Historie auf.
. while Akteur hat noch nicht alle Informationen, die er braucht
  * Der Nutzer ändert die Filterkriterien für die Einträge (siehe Unterablauf).
  * ODER
  * Der Nutzer lässt sich ältere Einträge anzeigen, indem er die Seite wechselt.
. end while
. Der Use Case ist abgeschlossen.

=== Unterabläufe (subflows)
//Nutzen Sie Unterabläufe, um wiederkehrende Schritte auszulagern

==== Filterkriterien ändern
. Der Akteur entscheidet sich dazu, die Historie nach bestimmten Kriterien zu filtern.
. Der Akteur gibt die entsprechenden Filterkriterien ein und teilt dem System mit, dass es alle Einträge basierend auf diesen Kriterien auflisten soll.
. Das System listet die letzten n Einträge der Historie auf, die den Filterkriterien entsprechen.

=== Besondere Anforderungen
//Besondere Anforderungen können sich auf nicht-funktionale Anforderungen wie z.B. einzuhaltende Standards, Qualitätsanforderungen oder Anforderungen an die Benutzeroberfläche beziehen.
==== Unterteilung in Seiten (Pagination)
* Damit nicht immer die gesamte Historie geladen werden muss, sollten zunächst nur die letzten n Einträge angezeigt werden.
* Mittels einer Pagination (Menü zum Wechseln von Seiten) kann der Nutzer auch ältere Einträge sehen, die nur bei Bedarf geladen werden.

