//Nutzen Sie dieses Template als Grundlage für die Spezifikation *einzelner* Use-Cases. Diese lassen sich dann per Include in das Use-Case Model Dokument einbinden (siehe Beispiel dort).
== Use-Case: Systemnutzer verwalten
===	Kurzbeschreibung
Als Administrator des Systems und Mitglied der internen Verwaltung des StuRas +
möchte ich Systemnutzer hinzufügen, bearbeiten und löschen können.

===	Kurzbeschreibung der Akteure
==== Administrator des Systems
Der/die Administrator/in/en haben Vollzugriff auf das System und sind für die Verwaltung der Nutzerzugänge verantwortlich.

==== Interne Verwaltung des StuRas
Eines oder mehrere Mitglieder der internen Verwaltung sind für die Administration des Systems verantwortlich.

=== Vorbedingungen
//Vorbedingungen müssen erfüllt, damit der Use Case beginnen kann, z.B. Benutzer ist angemeldet, Warenkorb ist nicht leer...
* Der/die Administrator/in ist im System eingeloggt.

=== Standardablauf (Basic Flow)
//Der Standardablauf definiert die Schritte für den Erfolgsfall ("Happy Path")

. Der Use Case beginnt, wenn der/die Administrator/in die Oberfläche zur Verwaltung der Systemnutzer öffnet.
. while Administrator/in hat noch nicht alle Änderungen vorgenommen
.. Dem Akteur wird eine aktuelle Liste aller Systemnutzer angezeigt.
.. Es wird ausgewählt, ob ein Nutzer hinzugefügt, bearbeitet oder gelöscht werden soll.
.. Fortsetzung in den jeweiligen Unterabläufen (subflows).
. end while
. Der Use Case ist abgeschlossen.

=== Unterabläufe (subflows)
//Nutzen Sie Unterabläufe, um wiederkehrende Schritte auszulagern

==== Hinzufügen eines neuen Nutzers
. Der Admin wählt aus, dass er einen neuen Nutzer hinzufügen möchte.
. Der Admin vergibt einen Benutzernamen, ein Passwort (welches beim erstmaligen Login geändert werden muss) und ordnet den Systemnutzer dem entsprechenden StuRa-Mitglied zu.
. Der Admin bestätigt die Eingabe und es wird ihm/ihr die aktualisierte Systemnutzer-Liste angezeigt.

==== Ändern eines bestehenden Nutzers
. Der Admin wählt einen bestehenden Eintrag in der Systemnutzer-Liste aus.
. Der Admin wählt aus, dass er diesen Systemnutzer ändern möchte.
. Der Admin ändert den Nutzernamen, setzt das Passwort zurück und/oder ändert die Zuordnung zum entsprechenden StuRa-Mitglied.
. Der Admin bestätigt die Eingabe und es wird ihm/ihr die aktualisierte Systemnutzer-Liste angezeigt.

==== Löschen eines bestehenden Nutzers
. Der Admin wählt einen bestehenden Eintrag in der Systemnutzer-Liste aus.
. Der Admin wählt aus, dass er diesen Systemnutzer löschen möchte.
. Der Admin bestätigt die Sicherheitsabfrage und es wird ihm/ihr die aktualisierte Systemnutzer-Liste angezeigt.

===	Nachbedingungen
//Nachbedingungen beschreiben das Ergebnis des Use Case, z.B. einen bestimmten Systemzustand.
==== Hinzufügen eines neuen Nutzers
. Falls ein neuer Nutzer hinzugefügt wurde, so wird dieses als neuer Datensatz in der Nutzerdatenbank gespeichert.
. Der Nutzer hat mit den angegebenen Anmeldedaten Zugriff auf das System.

==== Änderung eines bestehenden Nutzers
. Falls ein Nutzer geändert wurde, sind die geänderten Daten in der Nutzerdatenbank gespeichert.
. Der Nutzer hat mit den geänderten Anmeldedaten Zugriff auf das System, aber nicht mehr mit den alten Daten.

==== Löschen eines bestehenden Nutzers
. Falls ein Nutzer gelöscht wurde, so wurde sein Datensatz aus der Nutzerdatenbank entfernt.
. Der gelöschte Nutzer hat keinen Zugriff mehr auf das System.

=== Besondere Anforderungen
//Besondere Anforderungen können sich auf nicht-funktionale Anforderungen wie z.B. einzuhaltende Standards, Qualitätsanforderungen oder Anforderungen an die Benutzeroberfläche beziehen.
. Gespeicherte Anmeldedaten, insbesondere Passwörter, sollten niemals im Klartext in der Nutzerdatenbank vorliegen und es sollte niemals mit Klartextdaten gearbeitet werden.
. Vor dem Löschen eines Systemnutzers hat eine Sicherheitsabfrage zu erfolgen.


