Lukas Hirsch (LHi)
==================

Am Anfang des Projektes, besaß ich nur mittelmäßige Python kenntnisse, die
ich in diesem Projekt gut vertiefen konnte. Weiterhin fande ich es gut
mich mit der MVC-Architektur von Django als Webframework außeinanderzusetzen
und ihre besonderheiten zu erlernen.

Aus neugier hatte ich mich für die Rolle Tester entschieden, da ich mich auch
dafür interresiert habe, wie die Tests in einem Softwareprojekt ablaufen
und da ich in meinem Werkstudentenjob auch die Rolle Tester besetzen durfte.
Für mich das Schwierigste in meiner Rolle war es, die UI-Tests mit Selenium
so zu konzipieren, dass sie längerfristig bestand haben und ich diese nicht
mit jedem kleinen Update anpassen muss.

Außerdem fande ich es gut mal an einem Softwareprojekt in einer größeren Gruppe
mitzuwirken, was ich für mich als sehr angenehm empfand. Im Vergleich zu meinen
privaten Softwareprojekten empfand ich den entstandenen Code um einiges
qualitativ hochwertiger und vorallem lesbarer.

Ich bin mit dem Projektverlauf sehr zufrieden. Trotz Corona-Pandemie haben
wir meiner Meinung nach ein soliedes Softwaresystem auf die Beine gestellt.
Wir haben uns alle gut verstanden, auch mit unseren Stakeholdern haben wir
uns gut verstanden, was zu einem angenehmen Klima beisteuerte.

Zum Schluss möchte ich mich bei Ihnen als Professor und der HTW-Dresden für
diese Möglichkeit ein Softwaresystem colaborativ zu entwickeln bedanken.
