Benjamin Hempel (BHe)
=====================

Insgesamt bin ich mit dem Projektverlauf zufrieden. Besonders stolz bin ich darauf, dass unser Softwaresystem vom Kunden so gut aufgenommen wurde und wahrscheinlich sogar in den Produktiveinsatz kommen wird. Ich bin auch stolz darauf, dass das Endprodukt bezüglich der Nutzererfahrung und des User Interface relativ hochwertig und sogar mobile-friendly geworden ist.

Im Rahmen des Projekts bin ich erstmals mit Python und dem Web-Framework Django in Berührung gekommen. Ich hatte damit die Möglichkeit (und auch die Aufgabe), eine neue Programmiersprache in Verbindung mit einem neuen Web-Framework zu erlernen, auch wenn mir das von Django eingesetzte MVC-Pattern bereits von Ruby on Rails bekannt war. Die größere Erfahrung für mich war jedoch, erstmals in einem größeren Team zu arbeiten. Bisher habe ich, sowohl auf Arbeit als auch privat, nur allein oder mit einer anderen Person zusammen an einem Projekt gearbeitet. Im Rahmen des Projekts konnte ich somit erstmals die Vorzüge (wie z.B. die Möglichkeit, von mehreren Personen Feedback oder Hilfe zu einem Problem erhalten zu können), als auch die Nachteile (wie z.B. Merge-Konflikte oder unterschiedliche Meinungen zu einem Thema) von Teamarbeit erleben.

Gut funktioniert hat meiner Meinung nach die Zusammenarbeit im Team. Für jede anstehende Aufgabe hat sich ein/e Freiwillige/r gefunden, welche/r die Aufgabe dann auch gewissenhaft und rechtzeitig erledigt hat. Dadurch war es nicht erforderlich, jemandem Aufgaben aufzuzwingen und es kam auch zu keiner "Arbeitsverweigerung". Insgesamt gestalteten sich die Teammeetings dadurch relativ entspannt. Auch das Vieraugenprinzip unter Einsatz von Pull-Requests hat gut funktioniert, da so grobe Fehler noch vor dem eigentlichen Testen aufgefallen sind und damit eine höhere Qualität der Benutzererfahrung erzielt werden konnte. Ebenfalls gut funktioniert hat die Nutzung von Trello als zentrales Verwaltungstool, da hier alle Aufgaben übersichtlich auf einem Blick mit ihrem aktuellen Status zu sehen waren.

Verbesserungswürdig waren meiner Meinung nach insbesondere die Commit Messages. Hier kam es immer wieder zu Messages wie "Update <Dateiname>" oder "Small fix", welche nicht wirklich aussagekräftig sind. Ebenso verbesserungswürdig ist meiner Meinung nach die Codequalität. Das liegt jedoch daran, dass Django für die Meisten von uns ein neues Framework und somit auch das MVC-Pattern noch unbekannt war. Insbesondere fehlt unserem Code eine konsistente Benennung von Bezeichnern, da hier mit der Zeit eine unübersichtliche Mischung aus Deutsch und Englisch entstanden ist. Auch Prinzipien wie Separation of Concerns oder die strikte Einhaltung der durch Django vorgegebenen Architektur wurden nicht immer umgesetzt. Dies könnte eine zukünftige Entwicklung erschweren; ich hoffe aber, dass unsere meiner Meinung nach recht gut gelungende Code-Dokumentation hier Abhilfe schaffen kann.
