= Vision StuRa Mitgliederdatenbank
Lukas Hirsch <s79199@htw-dresden.de>
Theresa Schüttig <s79136@htw-dresden.de>
:toc:


== Einführung
Der Zweck dieses Dokuments ist es, die wesentlichen Bedarfe und Funktionalitäten der Mitgliederdatenbank für den StuRa zu sammeln, zu analysieren und zu definieren. Der Fokus liegt auf den Fähigkeiten, die von Stakeholdern und adressierten Nutzern benötigt werden, und der Begründung dieser Bedarfe. Die  Details, wie die Mitgliederdatenbank diese Bedarfe erfüllt, werden in der Use-Case und Supplementary Specification beschrieben.

=== Zweck
Der Zweck dieses Dokuments ist es, die wesentlichen Anforderungen an das System aus Sicht und mit den Begriffen der künftigen Anwender zu beschreiben.

=== Gültigkeitsbereich (Scope)
Dieses Visions-Dokument bezieht sich auf die StuRa-Mitgliederdatenbank, das vom in dieser link:../documentation.pdf[Datei] aufgelisteten Team entwickelt wird. Das System wird es Mitgliedern der Referate Verwaltung und Präsidium sowie Mitarbeitern des StuRas erlauben, Daten von Mitgliedern des StuRas über eine Webanwendung zu verwalten, um Informationen zu Mitgliedern, Ämtern und Wahlen zu speichern und einzusehen, einen Arbeitsleitfaden für die interne Verwaltung sowie eine Checkliste zu generieren. Im Idealfall sollte die Anwendung auch das https://www.stura.htw-dresden.de/stura/ref/personal/posten/plenum/stellenplan-organigramm-2019[hier] veröffentlichte Organigramm erzeugen können. 

=== Definitionen, Akronyme und Abkürzungen
siehe link:glossary.adoc[Glossar]

=== Referenzen
link:../orga/task.adoc[Aufgabenstellung]

== Positionierung

=== Fachliche Motivation
Derzeit werden Mitgliederdaten des StuRas über eine Excel-Tabelle verwaltet. Die StuRa-Mitgliederdatenbank soll die Verwaltung von Mitgliedern im StuRa erleichtern und übersichtlicher gestalten, indem Mitglieder sowie Referate und Ämter über eine benutzerfreundliche Website verwaltet werden können. Zudem soll über eine Historie ersichtlich sein, wann in der Datenbank von wem welche Änderungen vorgenommen wurden. Für die interne Verwaltung soll das Programm eine Checkliste mit Aufgaben (z.B. zum Mailverteiler hinzufügen, Zugang zum Schlüsselgang einrichten, etc.) erstellen können. Des Weiteren sollen die Software in der Lage sein, Anwesenheitslisten sowie das Organigramm zu generieren.

=== Problem Statement

|===
|Das Problem |	Die Excel-Tabelle ist unübersichtlich und die Bearbeitung erfordert zu viel Aufwand
|betrifft |	die interne Verwaltung
|die Auswirkung davon ist |	zu viel unnötiger Arbeitsaufwand
|eine erfolgreiche Lösung wäre |	Über eine Webseite könnte das Bearbeiten nur über das Aufüllen von ein paar Textfeldern ermöglicht werden
|===

|===
|Das Problem |	Es ist nicht möglich, herauszufinden, von wem bestimmte Änderungen vorgenommen wurden
|betrifft |	die interne Verwaltung
|die Auswirkung davon ist |	Verantwortliche für inkorrekte Änderungen können nicht ausfindig gemacht werden und Wiederherstellen korrekter Daten kann sich schwierig gestalten
|eine erfolgreiche Lösung wäre |	das Erstellen einer Historie
|===

|===
|Das Problem |	Das Erteilen von Zugängerechten ist unorganisiert
|betrifft |	die interne Verwaltung, StuRa-Mitglieder
|die Auswirkung davon ist |	die Verwaltung hat einen schlechten Überblick über noch zu erteilende Zugängge und StuRa-Mitglieder müssen auf Zugänge länger warten als nötig
|eine erfolgreiche Lösung wäre |	das Erstellen eines Arbeitsleitfadens für die interne Verwaltung
|===


=== Positionierung des Produkts 
//Ein Positionierung des Produkts beschreibt das Einsatzziel der Anwendung und die Bedeutung das Projekts an alle beteiligten Mitarbeiter.

//Geben Sie in knapper Form übersichtsartig die Positionierung der angestrebten Lösung im Vergleich zu verfügbaren Alternativen dar. Das folgende Format kann dazu verwendet werden:

|===
|Für|	Referat Verwaltung (StuRa)
|welchem|	das Verwalten der Mitglieder deutlich erleichtert wird
|Die Lösung ist eine | Webanwedung zur Mitgliederverwaltung
|Die / Das	|das Verwalten übersichtlicher gestaltet und eine Historie speichert
|Im Gegensatz zu	|Excel-Tabelle
|Unser Produkt|	zeigt nur abgefragte Daten an und ermöglicht das Hinzufügen und Bearbeiten in kürzerer Zeit
|===


==	Stakeholder Beschreibungen
===	Zusammenfassung der Stakeholder 

[%header]
|===
|Name|	Beschreibung	| Verantwortlichkeiten
|Verwaltung des StuRas	|selbsterklärend	|Eintragen von Mitgliedern, Dokumentieren von Wahlen, Einrichten von Zugängen
|Präsidium	|Das Präsidium ist zuständig für Sitzungen des StuRas	| Dokumentieren von Anwesenheit
|Mitglieder des StuRas	| Studierende der HTW, die vom StuRa in ein Amt gewählt wurden | Lesen von Daten aller Mitglieder
|===

=== Benutzerumgebung
Beschreiben Sie die Arbeitsumgebung des Nutzers. Hier sind einige Anregungen:

* Der StuRa hat derzeit 80 Mitglieder, von denen alle auf die Anwendung zugreifen können sollten. Diese Anzahl kann innerhalb der nächsten Jahre variieren.
* Wie lange dauert die Bearbeitung der Aufgabe? Wie viel Zeit wird für jeden Arbeitsschritt benötigt? Ändert sich das?
* Derzeit eingesetze Anwendung: Excel
* link:https://www.stura.htw-dresden.de/stura/ref/personal/posten/plenum/stellenplan-organigramm-2019[Organigramm]
