# Thema 8: Mitgliederdatenbank für den StuRa
:toc:

## Kontakt
sp@stura.htw-dresden.de +
verwaltung@stura.htw-dresden.de +
Tino Köhler +
Sophia von Asow

## Hintergrund
Der StuRa ist eine Teilkörperschaft öffentlichen Rechts, in der großer Mitgliederzahlen mit hoher
Fluktuation verwaltet werden müssen. Bisher läuft die Organisation über eine Tabelle, die der
heutigen Zeit nicht gerecht wird.

## Zielstellung
Es soll eine Datenbank erstellt werden, in der die relevanten Informationen (Personen, Ämter,
Amtszeiten,...) gespeichert sind. Die Verwaltungsoberfläche sollte webbasierte und
anwendungsfreundlich sein.

## Anforderungen
### Funktionale Anforderungen
* Anlegen von neuen Mitgliedern und Verwaltung bestehender Legislatur (von, bis,
Bezeichnung)
* Ämter (inkl. Workload)-nochmal dazwischengeschaltet: Amt ID, Mitglieder ID oder Leitung
oder Stellvertretung
* Wahlen (ID, Kandidatur Datum, Wahl Datum, Beschluss Nummer, Amt, Rücktrittsdatum)
* Aufwandsentschädigung (Erfüllungsgrad der Aufgaben, Mitglieder ID, Amt ID, Periode)
* Historie (alle Änderungen)
* Ausgabe eines Arbeitsleitfadens für die interne Verwaltung (Checkliste)
* Generierung Checkliste: Emailverteiler, Schlüsselkasten, Zugangsschließsystem, Berechtigung
Website/Dateiverwaltung/Aufgabenverwaltung, notwendige Unterschriften
* Generierung vom Organigramm (https://www.stura.htw-dresden.de/stura/ref/personal/posten/plenum/stellenplan-organigramm-2019 )

### Technische und organisatorische Rahmenbedingungen
* als Webanwendung und anwenderfreundlich
* kein Java und möglichst kein PHP
* freie Lizenz benutzen (z.B GPL, MIT, Apache)
* muss auf Linux/Unix laufen
* Gern auch in einem bekannten Webframework

### Dokumentation
Für die Entwicklung sind entsprechende Dokumente anzufertigen.

* Entwickler‐ und Benutzerdokumentation
* Testdokumentation
* Projektdokumentation
* Änderungen der Anforderungen
Für die Entwicklung können Sie nach Absprache Werkzeuge und Technologien Ihrer Wahl nutzen, sofern sie den Anforderungen aus Kundensicht entsprechen.
